# Generated by Django 6.0 on 2025-12-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='clearing_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='signal_recommendation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
