# Generated by Django 6.0 on 2025-12-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_app', '0002_processingresult_clearing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='signal_green_extension',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='signal_pattern',
            field=models.CharField(default='', max_length=100),
        ),
    ]
