# Generated by Django 6.0 on 2025-12-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_app', '0003_processingresult_signal_green_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='count_bikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='count_buses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='count_cars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='count_trucks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='signal_green_extension',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='signal_pattern',
            field=models.CharField(default='', max_length=50),
        ),
    ]
