# Generated by Django 6.0 on 2025-12-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_app', '0004_processingresult_count_bikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingresult',
            name='signal_pattern',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='signal_recommendation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
